import eliceLogo from '../src/images/logos/elice.png';
import wecodeLogo from '../src/images/logos/wecode.png';
import fastCampusLogo from '../src/images/logos/fastCampus.png';
import teamNovaLogo from '../src/images/logos/teamNova.png';
import codeStatesLogo from '../src/images/logos/codeStates.png';
import codeSquadLogo from '../src/images/logos/codeSquad.png';
import vanillaCodingLogo from '../src/images/logos/vanillaCoding.png';
import hanghae99Logo from '../src/images/logos/hanghae99.png';
import ninezerofactoryLogo from '../src/images/logos/90factory.png';
import codeCampLogo from '../src/images/logos/codeCamp.png';
import boostcampLogo from '../src/images/logos/boostcamp.png';
import likelionLogo from '../src/images/logos/likelion.png';
import seoul42Logo from '../src/images/logos/42seoul.png';
import ssafyLogo from '../src/images/logos/ssafy.png';
import risingCampLogo from '../src/images/logos/risingCamp.png';
import programmersLogo from '../src/images/logos/programmers.png';
import wooahanLogo from '../src/images/logos/wooahan.png';

export const data = [
  {
    id: 'elice',
    name: '엘리스 SW 아카데미',
    image: eliceLogo,
    star: 5.0,
    location: '서울시 강남구 선릉로 433 세방빌딩 6층',
    homepage: 'https://elicetrack.oopy.io/',
    system: '온라인 방식',
    review: [
      {
        creator: 'ifdfdsf',
        pros: '잘 가르쳐주십니다. 탄탄한 커리큘럼',
        cons: '딱히 없음',
        star: 4.5,
        timeStamp: '2021.01.22',
      },
      {
        creator: '엘리스짱',
        pros: '적절한 시간배분, 좋은 팀원들과의 프로젝트 경험이 아주 좋았습니다.',
        cons: '너무 잘 챙겨준다?',
        star: 5,
        timeStamp: '2021.01.26',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '단점은 없습니다.',
        star: 4,
        timeStamp: '2021.02.04',
      },
    ],
  },
  {
    id: 'wecode',
    name: '위코드',
    image: wecodeLogo,
    star: 4.5,
    location: '서울특별시 강남구 테헤란로 427, 위워크타워',
    homepage: 'https://wecode.co.kr/',
    system: '온라인 + 오프라인 방식',
    review: [
      {
        creator: 'qfdfdsf',
        pros: '잘 가르쳐주십니다. 탄탄한 커리큘럼',
        cons: '딱히 없음',
        star: 4.5,
        timeStamp: '2021.01.22',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 3,
        timeStamp: '2021.02.04',
      },
    ],
  },
  {
    id: 'fastcampus',
    name: '패스트캠퍼스',
    image: fastCampusLogo,
    star: 3.5,
    location:
      '서울특별시 강남구 강남대로 364 미왕빌딩 10, 11층 (강남역 신분당선 도보 1분 거리)',
    homepage: 'https://fastcampus.co.kr/gov',
    system: '오프라인 방식',
    review: [],
  },
  {
    id: 'teamnova',
    name: '팀노바',
    image: teamNovaLogo,
    star: 3.5,
    location: '서울특별시 동작구 사당동 318-13 (7호선 남성역 도보 5분거리 )',
    homepage: 'https://teamnova.co.kr/index2.php',
    system: '오프라인 방식',
    review: [
      {
        creator: 'ifdfdsf',
        pros: '잘 가르쳐주십니다. 탄탄한 커리큘럼',
        cons: '딱히 없음',
        star: 4.5,
        timeStamp: '2021.01.22',
      },
      {
        creator: '엘리스짱',
        pros: '적절한 시간배분, 좋은 팀원들과의 프로젝트 경험이 아주 좋았습니다.',
        cons: '너무 잘 챙겨준다?',
        star: 5,
        timeStamp: '2021.01.26',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.04',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.05',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.09',
      },
    ],
  },
  {
    id: 'codestates',
    name: '코드스테이츠',
    image: codeStatesLogo,
    star: 3.5,
    location:
      '서울특별시 서초구 서초대로 396, 강남빌딩 20층 (스파크플러스 강남2호점)',
    homepage: 'https://www.codestates.com/',
    system: '온라인 방식',
    review: [
      {
        creator: 'ifdfdsf',
        pros: '잘 가르쳐주십니다. 탄탄한 커리큘럼',
        cons: '딱히 없음',
        star: 4.5,
        timeStamp: '2021.01.22',
      },
      {
        creator: '엘리스짱',
        pros: '적절한 시간배분, 좋은 팀원들과의 프로젝트 경험이 아주 좋았습니다.',
        cons: '너무 잘 챙겨준다?',
        star: 5,
        timeStamp: '2021.01.26',
      },
    ],
  },
  {
    id: 'codesquad',
    name: '코드스쿼드',
    image: codeSquadLogo,
    star: 3.5,
    location: '서울특별시 강남구 역삼동 836-24 역삼빌딩 4층',
    homepage: 'https://codesquad.kr/',
    system: '오프라인 방식',
    review: [
      {
        creator: 'ifdfdsf',
        pros: '잘 가르쳐주십니다. 탄탄한 커리큘럼',
        cons: '딱히 없음',
        star: 4.5,
        timeStamp: '2021.01.22',
      },
      {
        creator: '엘리스짱',
        pros: '적절한 시간배분, 좋은 팀원들과의 프로젝트 경험이 아주 좋았습니다.',
        cons: '너무 잘 챙겨준다?',
        star: 5,
        timeStamp: '2021.01.26',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.04',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.05',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.09',
      },
    ],
  },
  {
    id: 'vanillacoding',
    name: '바닐라코딩',
    image: vanillaCodingLogo,
    star: 3.5,
    location: '서울특별시 강남구 테헤란로 522',
    homepage: 'https://www.vanillacoding.co/',
    system: '오프라인 방식',
    review: [
      {
        creator: 'ifdfdsf',
        pros: '잘 가르쳐주십니다. 탄탄한 커리큘럼',
        cons: '딱히 없음',
        star: 4.5,
        timeStamp: '2021.01.22',
      },
      {
        creator: '엘리스짱',
        pros: '적절한 시간배분, 좋은 팀원들과의 프로젝트 경험이 아주 좋았습니다.',
        cons: '너무 잘 챙겨준다?',
        star: 5,
        timeStamp: '2021.01.26',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.04',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.09',
      },
    ],
  },
  {
    id: 'spartacoding',
    name: '스파르타코딩 항해99',
    image: hanghae99Logo,
    star: 3.5,
    location: '서울특별시 강남구 논현로 425',
    homepage: 'https://hanghae99.spartacodingclub.kr/',
    system: '온라인 방식',
    review: [
      {
        creator: 'ifdfdsf',
        pros: '잘 가르쳐주십니다. 탄탄한 커리큘럼',
        cons: '딱히 없음',
        star: 4.5,
        timeStamp: '2021.01.22',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.09',
      },
    ],
  },
  {
    id: 'ninezero',
    name: '구공팩토리',
    image: ninezerofactoryLogo,
    star: 3.5,
    location: '서울 금천구 가산디지털1로 171 SK V1 센터',
    homepage: 'https://heungmelab.github.io/index.html',
    system: '온라인 + 오프라인 방식',
    review: [],
  },
  {
    id: 'codecamp',
    name: '코드캠프',
    image: codeCampLogo,
    star: 3.5,
    location: '서울시 구로구 디지털로 300, 패스트파이브 구로점 13층',
    homepage: 'https://codebootcamp.co.kr/',
    system: '오프라인 방식',
    review: [
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.09',
      },
    ],
  },
  {
    id: 'boostcamp',
    name: '네이버 부스트캠프',
    image: boostcampLogo,
    star: 2.5,
    location: '정보없음',
    homepage: 'https://boostcamp.connect.or.kr/',
    system: '온라인 방식',
    review: [
      {
        creator: 'ifdfdsf',
        pros: '잘 가르쳐주십니다. 탄탄한 커리큘럼',
        cons: '딱히 없음',
        star: 4.5,
        timeStamp: '2021.01.22',
      },
      {
        creator: '엘리스짱',
        pros: '적절한 시간배분, 좋은 팀원들과의 프로젝트 경험이 아주 좋았습니다.',
        cons: '너무 잘 챙겨준다?',
        star: 5,
        timeStamp: '2021.01.26',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.04',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.05',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.09',
      },
    ],
  },
  {
    id: 'likelion',
    name: '멋쟁이사자처럼',
    image: likelionLogo,
    star: 2.5,
    location: '서울특별시 강남구 테헤란로 302 위워크타워 20층',
    homepage: 'https://k-digital.likelion.net/',
    system: '온라인 + 오프라인 방식',
    review: [
      {
        creator: 'ifdfdsf',
        pros: '잘 가르쳐주십니다. 탄탄한 커리큘럼',
        cons: '딱히 없음',
        star: 4.5,
        timeStamp: '2021.01.22',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.09',
      },
    ],
  },
  {
    id: 'seoul42',
    name: '42 Seoul',
    image: seoul42Logo,
    star: 2.5,
    location: '서울시 강남구 개포로 416 이노베이션 아카데미',
    homepage: 'https://42seoul.kr/seoul42/main/view',
    system: '오프라인 방식',
    review: [
      {
        creator: 'ifdfdsf',
        pros: '잘 가르쳐주십니다. 탄탄한 커리큘럼',
        cons: '딱히 없음',
        star: 4.5,
        timeStamp: '2021.01.22',
      },
      {
        creator: '엘리스짱',
        pros: '적절한 시간배분, 좋은 팀원들과의 프로젝트 경험이 아주 좋았습니다.',
        cons: '너무 잘 챙겨준다?',
        star: 5,
        timeStamp: '2021.01.26',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 1,
        timeStamp: '2021.02.04',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.05',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 3,
        timeStamp: '2021.02.09',
      },
    ],
  },
  {
    id: 'ssafy',
    name: 'SSAFY 삼성청년SW 아카데미',
    image: ssafyLogo,
    star: 2.5,
    location: '서울시 강남구 테헤란로 212 서울캠퍼스 외 전국 4개',
    homepage: 'https://www.ssafy.com/',
    system: '온라인 + 오프라인 방식',
    review: [
      {
        creator: 'ifdfdsf',
        pros: '잘 가르쳐주십니다. 탄탄한 커리큘럼',
        cons: '딱히 없음',
        star: 4.5,
        timeStamp: '2021.01.22',
      },
      {
        creator: '엘리스짱',
        pros: '적절한 시간배분, 좋은 팀원들과의 프로젝트 경험이 아주 좋았습니다.',
        cons: '너무 잘 챙겨준다?',
        star: 5,
        timeStamp: '2021.01.26',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 5,
        timeStamp: '2021.02.04',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 5,
        timeStamp: '2021.02.05',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.09',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.09',
      },
    ],
  },
  {
    id: 'rising',
    name: '라이징캠프',
    image: risingCampLogo,
    star: 2.5,
    location: '서울특별시 마포구 공덕동 242-75 4층',
    homepage: 'https://risingcamp.com/',
    system: '온라인 방식',
    review: [
      {
        creator: 'ifdfdsf',
        pros: '잘 가르쳐주십니다. 탄탄한 커리큘럼',
        cons: '딱히 없음',
        star: 4.5,
        timeStamp: '2021.01.22',
      },
      {
        creator: '엘리스짱',
        pros: '적절한 시간배분, 좋은 팀원들과의 프로젝트 경험이 아주 좋았습니다.',
        cons: '너무 잘 챙겨준다?',
        star: 5,
        timeStamp: '2021.01.26',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.09',
      },
    ],
  },
  {
    id: 'programmers',
    name: '프로그래머스 데브코스',
    image: programmersLogo,
    star: 2.5,
    location:
      '서울특별시 서초구 강남대로 327, 2층 프로그래머스(서초동, 대륭서초타워)',
    homepage: 'https://programmers.co.kr/learn?tag=데브코스',
    system: '온라인 방식',
    review: [
      {
        creator: 'ifdfdsf',
        pros: '잘 가르쳐주십니다. 탄탄한 커리큘럼',
        cons: '딱히 없음',
        star: 4.5,
        timeStamp: '2021.01.22',
      },
      {
        creator: 'vzsfsda',
        pros: '짜임새 있는 커리큘럼과 좋은 코치진분들로 구성되어 있어 도움이 많이 되었습니다.',
        cons: '딱히 없는 것 같네요',
        star: 4,
        timeStamp: '2021.02.09',
      },
    ],
  },
  {
    id: 'wooahan',
    name: '우아한테크코스',
    image: wooahanLogo,
    star: 2.5,
    location: '잠실, 선릉에 캠퍼스 위치',
    homepage: 'https://woowacourse.github.io/',
    system: '오프라인 방식',
    review: [
      {
        creator: 'ifdfdsf',
        pros: '잘 가르쳐주십니다. 탄탄한 커리큘럼',
        cons: '딱히 없음',
        star: 4.5,
        timeStamp: '2021.01.22',
      },
      {
        creator: '엘리스짱',
        pros: '적절한 시간배분, 좋은 팀원들과의 프로젝트 경험이 아주 좋았습니다.',
        cons: '너무 잘 챙겨준다?',
        star: 5,
        timeStamp: '2021.01.26',
      },
    ],
  },
];
